server:
  port: 3001
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: big
    password: 1234
  jpa:
    hibernate:
      # 애플맅케이션 로딩 시점에 테이블 drop 후에 create
      ddl-auto: create
    properties:
      hibernate:
        # 쿼리 이쁘게 보기. system.out으로 출력
#        show_sql: true
        format_sql: true
#        use_sql_comments: true # Querydsl이 JPQL로 변환되는걸 보기 위해서. 하지만 에러난다...

logging.level:
  org.hibernate.SQL: debug # 로거로 출력
  # org.hibernate.type: trace

